name: Deploy to School Server

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Deploy to School Server
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SERVER_USER: ${{ secrets.SERVER_USER }}
                  SERVER_HOST: ${{ secrets.SERVER_HOST }}
                  SERVER_PATH: ${{ secrets.SERVER_PATH }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
                  ssh $SERVER_USER@$SERVER_HOST "mkdir -p $SERVER_PATH"
                  rsync -avz --delete dist/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH
